framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection:
        enabled: true

<<<<<<< HEAD
    csrf_protection: true

    form:
        csrf_protection:
            enabled: true
            field_name: _token

    #esi: true
    #fragments: true
=======
    session:
        enabled: true
>>>>>>> planning

    property_info:
        enabled: true
