framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection:
        enabled: true

    form:
        csrf_protection:
            enabled: true
            field_name: _token

    session:
        enabled: true

    #esi: true
    #fragments: true

    property_info:
        enabled: true
