framework:
    secret: '%env(APP_SECRET)%'
    
    # Configuration des sessions (nécessaire pour CSRF)
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    
    # Property Info
    property_info:
        enabled: true
    
    # Configuration HTTP
    http_method_override: true
    
    # Gestion des formulaires
    form: true
    
    # Validation
    validation:
        email_validation_mode: html5
    
    # Assets
    assets: true
    
    # PHP Errors
    php_errors:
        log: true