twig:
    file_name_pattern: '*.twig'
    globals:
        pusher_app_key: '%env(PUSHER_KEY)%'
        pusher_app_cluster: '%env(PUSHER_CLUSTER)%'

when@test:
    twig:
        strict_variables: true
