<<<<<<< HEAD
when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
=======
# Ce fichier peut rester vide ou contenir seulement vos routes spécifiques au framework
>>>>>>> planning
