# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.serpapi_key: '%env(SERPAPI_KEY)%'
    app.rapidapi_key: '%env(RAPIDAPI_KEY)%'
    app.rapidapi_host: '%env(RAPIDAPI_HOST)%'
    mailer_from_email: '%env(MAILER_FROM_EMAIL)%'
    mailer_from_name: '%env(MAILER_FROM_NAME)%'
    pusher.app_id: '%env(PUSHER_APP_ID)%'
    pusher.key: '%env(PUSHER_KEY)%'
    pusher.secret: '%env(PUSHER_SECRET)%'
    pusher.cluster: '%env(PUSHER_CLUSTER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

    App\Service\PusherService:
        arguments:
            $appId: '%pusher.app_id%'
            $key: '%pusher.key%'
            $secret: '%pusher.secret%'
            $cluster: '%pusher.cluster%'
